// <auto-generated />
using System;
using Caritas.Gestao.ServiceAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Caritas.Gestao.ServiceAPI.Migrations
{
    [DbContext(typeof(CaritasContext))]
    [Migration("20200827224653_ScheduleSheets")]
    partial class ScheduleSheets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Caritas.Gestao.ServiceAPI.Context.Kinship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KinName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kinships","shelt");
                });

            modelBuilder.Entity("Caritas.Gestao.ServiceAPI.Models.Responsible", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kinshipId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsibleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Responsibles","shelt");
                });

            modelBuilder.Entity("Caritas.Gestao.ServiceAPI.Models.ScheduleSheet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("interviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("kinshipId")
                        .HasColumnType("int");

                    b.Property<string>("observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsibleAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsibleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("responsiblePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("scheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("scheduleResponsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shelteredAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shelteredAge")
                        .HasColumnType("int");

                    b.Property<string>("shelteredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shelteredPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ScheduleSheets","shelt");
                });

            modelBuilder.Entity("Caritas.Gestao.ServiceAPI.Models.Sheltered", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("bloodTyping")
                        .HasColumnType("int");

                    b.Property<DateTime>("entryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perfilImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sheltereds","shelt");
                });

            modelBuilder.Entity("Caritas.Gestao.ServiceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users","usr");
                });
#pragma warning restore 612, 618
        }
    }
}
